[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "energy_prediction"
version = "0.1.0"
authors = [
    {name = "Brayan Steven Peña", email = "bspenad@unal.edu.co"}
]
description = "Modelo predictivo de consumo de energía utilizando metodología CRISP-DM y Random Forest."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn"
]

[tool.setuptools.packages.find]
where = ["src"]
